version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing dependencies...
      - npm ci

  build:
    commands:
      - echo Building the widget...
      - npm run build

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Copying files to S3...
      - aws s3 cp dist/ s3://$BUCKET_NAME/ --recursive

artifacts:
  files:
    - '**/*'
